plugins {
    id 'java'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'idea'
}

group = mod_group_id
version = mod_version

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neoforge_version

    parchment {
        mappingsVersion = project.mapping_version
        minecraftVersion = project.minecraft_version
    }

    mods {
        opensecurity {
            sourceSet sourceSets.main
        }
    }

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
        client { client() }
        server {
            server()
            programArgument '--nogui'
        }
        gameTestServer { type = 'gameTestServer' }
        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').absolutePath,
                    '--existing', file('src/main/resources/').absolutePath
        }
    }
}

sourceSets {
    main {
        java.setSrcDirs(['src/main/java'])
        resources.setSrcDirs(['src/main/resources', 'src/generated/resources', 'src/main/templates'])
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.neoforged.net/releases' }
}

def openComputersRoot = file('../OpenComputers')
def openComputersApi = file("${openComputersRoot}/build/libs/opencomputers-${opencomputers_version}-api.jar")
def openComputersRuntime = file("${openComputersRoot}/build/libs/opencomputers-${opencomputers_version}.jar")
def scalaLoaderRuntime = file("${openComputersRoot}/build/libs/scalablecatsforce-neoforge-${scala_loader_version}-with-library.jar")

dependencies {
    compileOnly files(openComputersApi, openComputersRuntime)
    runtimeOnly files(openComputersRuntime, scalaLoaderRuntime)
    implementation 'org.mindrot:jbcrypt:0.4'
}

tasks.named('processResources', ProcessResources).configure {
    def properties = [
            mod_id: mod_id,
            mod_name: mod_name,
            mod_version: mod_version,
            mod_license: mod_license,
            mod_authors: mod_authors,
            mod_description: mod_description,
            minecraft_version_range: minecraft_version_range,
            neoforge_version_range: neoforge_version_range,
            loader_version_range: loader_version_range,
            opencomputers_version_range: opencomputers_version_range
    ]
    inputs.properties properties
    filesMatching('META-INF/neoforge.mods.toml') { expand properties }
}

tasks.named('jar', Jar).configure {
    from('LICENSE') { into 'META-INF' }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) { from components.java }
    }
}
