org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G
org.gradle.configureondemand=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neoforge_version=21.1.233
neoforge_version_range=[21.1,)
mapping_version=2024.11.17

mod_id=opensecurity
mod_name=OpenSecurity
mod_group_id=pcl.opensecurity
mod_version=2.0.0
mod_license=MIT
mod_authors=PC-Logix and contributors
mod_description=Security devices and components for OpenComputers.
loader_version_range=[4,)
opencomputers_version=1.9.4
opencomputers_version_range=[1.9.0,)
curse_project_id=231687
opencomputers_curse_project_id=1634364
scala_loader_version=3.3.3-build-15
