local shell = require("shell")

shell.setAlias("dir", "ls")
shell.setAlias("list", "ls")
shell.setAlias("move", "mv")
shell.setAlias("rename", "mv")
shell.setAlias("copy", "cp")
shell.setAlias("del", "rm")
shell.setAlias("md", "mkdir")
shell.setAlias("cls", "clear")
shell.setAlias("less", "more")
shell.setAlias("rs", "redstone")
shell.setAlias("view", "edit -r")
shell.setAlias("help", "man")
shell.setAlias("?", "man")
shell.setAlias("cp", "cp -i")
shell.setAlias("usage", "df")
shell.setAlias("rmuser", "deluser")
shell.setAlias("reboot", "shutdown -r")
shell.setAlias("sudo", "/root/sudo.lua")
shell.setAlias("su", "/root/su.lua")

require("event").listen("init", function()
  local file = io.open("/etc/hostname")
  if file then
    os.setenv("HOSTNAME", file:read("*l"))
    file:close()
  end
end)
