local shell = require("shell")

shell.setAlias("dir", "ls")
shell.setAlias("list", "ls")
shell.setAlias("move", "mv")
shell.setAlias("rename", "mv")
shell.setAlias("copy", "cp")
shell.setAlias("del", "rm")
shell.setAlias("md", "mkdir")
shell.setAlias("cls", "clear")
shell.setAlias("less", "more")
shell.setAlias("rs", "redstone")
shell.setAlias("view", "edit -r")
shell.setAlias("help", "man")
shell.setAlias("?", "man")
shell.setAlias("cp", "cp -i")
shell.setAlias("usage", "/bin/usage.lua")
shell.setAlias("logout", "/bin/logout.lua")
shell.setAlias("update", "/bin/update.lua")
shell.setAlias("adduser", "/bin/adduser.lua")
shell.setAlias("deluser", "rmuser", "/bin/deluser.lua")
shell.setAlias("passwd", "/bin/passwd.lua")

require("event").listen("init", function()
  local file = io.open("/etc/hostname")
  if file then
    os.setenv("HOSTNAME", file:read("*l"))
    os.setenv("PS1", "$HOSTNAME:$PWD# ")
    file:close()
  end
end)
